/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IWETH__factory>
getContractFactory(name: 'OTC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OTC__factory>
getContractFactory(name: 'BatchTradeFiller', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BatchTradeFiller__factory>
getContractFactory(name: 'IOTCFill', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOTCFill__factory>
getContractFactory(name: 'CancelReentrantCreator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CancelReentrantCreator__factory>
getContractFactory(name: 'IOTC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOTC__factory>
getContractFactory(name: 'IReenterCallback', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReenterCallback__factory>
getContractFactory(name: 'MaliciousERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MaliciousERC20__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'MockWETH', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockWETH__factory>
getContractFactory(name: 'IOTCFillInEth', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IOTCFillInEth__factory>
getContractFactory(name: 'RejectEthReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RejectEthReceiver__factory>
getContractFactory(name: 'String', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.String__factory>

  getContractAt(name: 'IWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IWETH>
getContractAt(name: 'OTC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OTC>
getContractAt(name: 'BatchTradeFiller', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BatchTradeFiller>
getContractAt(name: 'IOTCFill', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOTCFill>
getContractAt(name: 'CancelReentrantCreator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CancelReentrantCreator>
getContractAt(name: 'IOTC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOTC>
getContractAt(name: 'IReenterCallback', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReenterCallback>
getContractAt(name: 'MaliciousERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MaliciousERC20>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'MockWETH', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockWETH>
getContractAt(name: 'IOTCFillInEth', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IOTCFillInEth>
getContractAt(name: 'RejectEthReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RejectEthReceiver>
getContractAt(name: 'String', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.String>

  deployContract(name: 'IWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'OTC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OTC>
deployContract(name: 'BatchTradeFiller', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BatchTradeFiller>
deployContract(name: 'IOTCFill', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOTCFill>
deployContract(name: 'CancelReentrantCreator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CancelReentrantCreator>
deployContract(name: 'IOTC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOTC>
deployContract(name: 'IReenterCallback', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReenterCallback>
deployContract(name: 'MaliciousERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaliciousERC20>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockWETH', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockWETH>
deployContract(name: 'IOTCFillInEth', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOTCFillInEth>
deployContract(name: 'RejectEthReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RejectEthReceiver>
deployContract(name: 'String', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.String>

  deployContract(name: 'IWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IWETH>
deployContract(name: 'OTC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OTC>
deployContract(name: 'BatchTradeFiller', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BatchTradeFiller>
deployContract(name: 'IOTCFill', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOTCFill>
deployContract(name: 'CancelReentrantCreator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CancelReentrantCreator>
deployContract(name: 'IOTC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOTC>
deployContract(name: 'IReenterCallback', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReenterCallback>
deployContract(name: 'MaliciousERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MaliciousERC20>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'MockWETH', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockWETH>
deployContract(name: 'IOTCFillInEth', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IOTCFillInEth>
deployContract(name: 'RejectEthReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RejectEthReceiver>
deployContract(name: 'String', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.String>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  