/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OTCInterface extends Interface {
    getFunction(nameOrSignature: "WETH" | "cancelTrade" | "cancelTrades" | "createTrade" | "createTradeFromETH" | "fillTrade" | "fillTradeInETH" | "totalTrades" | "trades"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TradeCancelled" | "TradeCreated" | "TradeFullyFilled" | "TradePartiallyFilled"): EventFragment;

    encodeFunctionData(functionFragment: 'WETH', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelTrade', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelTrades', values: [BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'createTrade', values: [AddressLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTradeFromETH', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fillTrade', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fillTradeInETH', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalTrades', values?: undefined): string;
encodeFunctionData(functionFragment: 'trades', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'WETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTrades', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTradeFromETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fillTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fillTradeInETH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalTrades', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trades', data: BytesLike): Result;
  }

  
    export namespace TradeCancelledEvent {
      export type InputTuple = [from: AddressLike, tradeID: BigNumberish];
      export type OutputTuple = [from: string, tradeID: bigint];
      export interface OutputObject {from: string, tradeID: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeCreatedEvent {
      export type InputTuple = [from: AddressLike, tradeID: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [from: string, tradeID: bigint, deadline: bigint];
      export interface OutputObject {from: string, tradeID: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeFullyFilledEvent {
      export type InputTuple = [from: AddressLike, tradeID: BigNumberish, giveToken: AddressLike, giveAmount: BigNumberish, wantToken: AddressLike, wantAmount: BigNumberish];
      export type OutputTuple = [from: string, tradeID: bigint, giveToken: string, giveAmount: bigint, wantToken: string, wantAmount: bigint];
      export interface OutputObject {from: string, tradeID: bigint, giveToken: string, giveAmount: bigint, wantToken: string, wantAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradePartiallyFilledEvent {
      export type InputTuple = [from: AddressLike, tradeID: BigNumberish, giveToken: AddressLike, giveAmount: BigNumberish, wantToken: AddressLike, wantAmount: BigNumberish];
      export type OutputTuple = [from: string, tradeID: bigint, giveToken: string, giveAmount: bigint, wantToken: string, wantAmount: bigint];
      export interface OutputObject {from: string, tradeID: bigint, giveToken: string, giveAmount: bigint, wantToken: string, wantAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface OTC extends BaseContract {
    
    connect(runner?: ContractRunner | null): OTC;
    waitForDeployment(): Promise<this>;

    interface: OTCInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    WETH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelTrade: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTrades: TypedContractMethod<
      [_ids: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    createTrade: TypedContractMethod<
      [_giveToken: AddressLike, _giveAmount: BigNumberish, _wantToken: AddressLike, _wantAmount: BigNumberish, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    createTradeFromETH: TypedContractMethod<
      [_wantToken: AddressLike, _wantAmount: BigNumberish, _deadline: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    fillTrade: TypedContractMethod<
      [_id: BigNumberish, _fillAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fillTradeInETH: TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    totalTrades: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    trades: TypedContractMethod<
      [_id: BigNumberish, ],
      [[string, bigint, bigint, string, bigint, string, bigint, bigint] & {creator: string, remainingWantAmount: bigint, remainingGiveAmount: bigint, giveToken: string, giveAmount: bigint, wantToken: string, wantAmount: bigint, timeout: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'WETH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelTrade'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTrades'): TypedContractMethod<
      [_ids: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTrade'): TypedContractMethod<
      [_giveToken: AddressLike, _giveAmount: BigNumberish, _wantToken: AddressLike, _wantAmount: BigNumberish, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTradeFromETH'): TypedContractMethod<
      [_wantToken: AddressLike, _wantAmount: BigNumberish, _deadline: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'fillTrade'): TypedContractMethod<
      [_id: BigNumberish, _fillAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fillTradeInETH'): TypedContractMethod<
      [_id: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'totalTrades'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'trades'): TypedContractMethod<
      [_id: BigNumberish, ],
      [[string, bigint, bigint, string, bigint, string, bigint, bigint] & {creator: string, remainingWantAmount: bigint, remainingGiveAmount: bigint, giveToken: string, giveAmount: bigint, wantToken: string, wantAmount: bigint, timeout: bigint }],
      'view'
    >;

    getEvent(key: 'TradeCancelled'): TypedContractEvent<TradeCancelledEvent.InputTuple, TradeCancelledEvent.OutputTuple, TradeCancelledEvent.OutputObject>;
getEvent(key: 'TradeCreated'): TypedContractEvent<TradeCreatedEvent.InputTuple, TradeCreatedEvent.OutputTuple, TradeCreatedEvent.OutputObject>;
getEvent(key: 'TradeFullyFilled'): TypedContractEvent<TradeFullyFilledEvent.InputTuple, TradeFullyFilledEvent.OutputTuple, TradeFullyFilledEvent.OutputObject>;
getEvent(key: 'TradePartiallyFilled'): TypedContractEvent<TradePartiallyFilledEvent.InputTuple, TradePartiallyFilledEvent.OutputTuple, TradePartiallyFilledEvent.OutputObject>;

    filters: {
      
      'TradeCancelled(address,uint256)': TypedContractEvent<TradeCancelledEvent.InputTuple, TradeCancelledEvent.OutputTuple, TradeCancelledEvent.OutputObject>;
      TradeCancelled: TypedContractEvent<TradeCancelledEvent.InputTuple, TradeCancelledEvent.OutputTuple, TradeCancelledEvent.OutputObject>;
    

      'TradeCreated(address,uint256,uint256)': TypedContractEvent<TradeCreatedEvent.InputTuple, TradeCreatedEvent.OutputTuple, TradeCreatedEvent.OutputObject>;
      TradeCreated: TypedContractEvent<TradeCreatedEvent.InputTuple, TradeCreatedEvent.OutputTuple, TradeCreatedEvent.OutputObject>;
    

      'TradeFullyFilled(address,uint256,address,uint256,address,uint256)': TypedContractEvent<TradeFullyFilledEvent.InputTuple, TradeFullyFilledEvent.OutputTuple, TradeFullyFilledEvent.OutputObject>;
      TradeFullyFilled: TypedContractEvent<TradeFullyFilledEvent.InputTuple, TradeFullyFilledEvent.OutputTuple, TradeFullyFilledEvent.OutputObject>;
    

      'TradePartiallyFilled(address,uint256,address,uint256,address,uint256)': TypedContractEvent<TradePartiallyFilledEvent.InputTuple, TradePartiallyFilledEvent.OutputTuple, TradePartiallyFilledEvent.OutputObject>;
      TradePartiallyFilled: TypedContractEvent<TradePartiallyFilledEvent.InputTuple, TradePartiallyFilledEvent.OutputTuple, TradePartiallyFilledEvent.OutputObject>;
    
    };
  }