/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from './interfaces/index.js';
export * as test from './test/index.js';
export * as utils from './utils/index.js';
export { OTC__factory } from './OTC__factory.js';