/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IOTCFillInEth, IOTCFillInEthInterface } from "../../../test/RejectEthReceiver.sol/IOTCFillInEth.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_id",
        "type": "uint256"
      }
    ],
    "name": "fillTradeInETH",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  }
] as const;

  export class IOTCFillInEth__factory {
    static readonly abi = _abi;
    static createInterface(): IOTCFillInEthInterface {
      return new Interface(_abi) as IOTCFillInEthInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IOTCFillInEth {
      return new Contract(address, _abi, runner) as unknown as IOTCFillInEth;
    }
  }
  