/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { RejectEthReceiver, RejectEthReceiverInterface } from "../../../test/RejectEthReceiver.sol/RejectEthReceiver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "otc",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      }
    ],
    "name": "fillViaContract",
    "outputs": [],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061019e8061001c5f395ff3fe608060405260043610610020575f3560e01c80638d83ef4e1461008f575f5ffd5b3661008b576040517f08c379a000000000000000000000000000000000000000000000000000000000815260206004820152601360248201527f4e6f20726566756e647320616363657074656400000000000000000000000000604482015260640160405180910390fd5b5f5ffd5b6100a261009d366004610126565b6100a4565b005b6040517f1ecc7e750000000000000000000000000000000000000000000000000000000081526004810182905273ffffffffffffffffffffffffffffffffffffffff831690631ecc7e759034906024015f604051808303818588803b15801561010b575f5ffd5b505af115801561011d573d5f5f3e3d5ffd5b50505050505050565b5f5f60408385031215610137575f5ffd5b823573ffffffffffffffffffffffffffffffffffffffff8116811461015a575f5ffd5b94602093909301359350505056fea26469706673582212202e0cbea489f429e4f3a704713bcd78de1035304d03a6429eff914cc0b302595864736f6c634300081c0033";

  
      type RejectEthReceiverConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: RejectEthReceiverConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class RejectEthReceiver__factory extends ContractFactory {
    
      constructor(...args: RejectEthReceiverConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<RejectEthReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): RejectEthReceiver__factory {
      return super.connect(runner) as RejectEthReceiver__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): RejectEthReceiverInterface {
      return new Interface(_abi) as RejectEthReceiverInterface;
    }
    
    override attach(address: string | Addressable): RejectEthReceiver {
      return super.attach(address) as RejectEthReceiver;
    }
  static connect(address: string, runner?: ContractRunner | null): RejectEthReceiver {
      return new Contract(address, _abi, runner) as unknown as RejectEthReceiver;
    }
  }

  
  