/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface CancelReentrantCreatorInterface extends Interface {
    getFunction(nameOrSignature: "attackCancel" | "otc" | "reenterCallback" | "reenterReverted" | "setupTrade" | "tradeId"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'attackCancel', values?: undefined): string;
encodeFunctionData(functionFragment: 'otc', values?: undefined): string;
encodeFunctionData(functionFragment: 'reenterCallback', values?: undefined): string;
encodeFunctionData(functionFragment: 'reenterReverted', values?: undefined): string;
encodeFunctionData(functionFragment: 'setupTrade', values: [AddressLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tradeId', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'attackCancel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'otc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reenterCallback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reenterReverted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setupTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tradeId', data: BytesLike): Result;
  }

  

  export interface CancelReentrantCreator extends BaseContract {
    
    connect(runner?: ContractRunner | null): CancelReentrantCreator;
    waitForDeployment(): Promise<this>;

    interface: CancelReentrantCreatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    attackCancel: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    otc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reenterCallback: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reenterReverted: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setupTrade: TypedContractMethod<
      [giveToken: AddressLike, giveAmount: BigNumberish, wantToken: AddressLike, wantAmount: BigNumberish, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tradeId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'attackCancel'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'otc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reenterCallback'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reenterReverted'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setupTrade'): TypedContractMethod<
      [giveToken: AddressLike, giveAmount: BigNumberish, wantToken: AddressLike, wantAmount: BigNumberish, deadline: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tradeId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }