/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IOTCInterface extends Interface {
    getFunction(nameOrSignature: "cancelTrade" | "createTrade"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'cancelTrade', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTrade', values: [AddressLike, BigNumberish, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'cancelTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTrade', data: BytesLike): Result;
  }

  

  export interface IOTC extends BaseContract {
    
    connect(runner?: ContractRunner | null): IOTC;
    waitForDeployment(): Promise<this>;

    interface: IOTCInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelTrade: TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTrade: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, arg3: BigNumberish, arg4: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelTrade'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTrade'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike, arg3: BigNumberish, arg4: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }