/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IOTCFill, IOTCFillInterface } from "../../../test/BatchTradeFiller.sol/IOTCFill.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_id",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_fillAmount",
        "type": "uint256"
      }
    ],
    "name": "fillTrade",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IOTCFill__factory {
    static readonly abi = _abi;
    static createInterface(): IOTCFillInterface {
      return new Interface(_abi) as IOTCFillInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IOTCFill {
      return new Contract(address, _abi, runner) as unknown as IOTCFill;
    }
  }
  