/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReenterCallback, IReenterCallbackInterface } from "../../../test/MaliciousERC20.sol/IReenterCallback.js";

  const _abi = [
  {
    "inputs": [],
    "name": "reenterCallback",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IReenterCallback__factory {
    static readonly abi = _abi;
    static createInterface(): IReenterCallbackInterface {
      return new Interface(_abi) as IReenterCallbackInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReenterCallback {
      return new Contract(address, _abi, runner) as unknown as IReenterCallback;
    }
  }
  