/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOTCFillInEth } from './IOTCFillInEth.js';
export type { RejectEthReceiver } from './RejectEthReceiver.js';