/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface BatchTradeFillerInterface extends Interface {
    getFunction(nameOrSignature: "approveToken" | "batchFill"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'approveToken', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'batchFill', values: [AddressLike, BigNumberish[], BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'approveToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchFill', data: BytesLike): Result;
  }

  

  export interface BatchTradeFiller extends BaseContract {
    
    connect(runner?: ContractRunner | null): BatchTradeFiller;
    waitForDeployment(): Promise<this>;

    interface: BatchTradeFillerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveToken: TypedContractMethod<
      [token: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    batchFill: TypedContractMethod<
      [otc: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveToken'): TypedContractMethod<
      [token: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'batchFill'): TypedContractMethod<
      [otc: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }