/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { String, StringInterface } from "../../utils/String.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "_role",
        "type": "string"
      }
    ],
    "name": "getRoleHash",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x610142610034600b8282823980515f1a607314602857634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610610034575f3560e01c8063f275f1af14610038575b5f5ffd5b61004b61004636600461008f565b61005d565b60405190815260200160405180910390f35b5f82826040516020016100719291906100fd565b60405160208183030381529060405280519060200120905092915050565b5f5f602083850312156100a0575f5ffd5b823567ffffffffffffffff8111156100b6575f5ffd5b8301601f810185136100c6575f5ffd5b803567ffffffffffffffff8111156100dc575f5ffd5b8560208284010111156100ed575f5ffd5b6020919091019590945092505050565b818382375f910190815291905056fea2646970667358221220574266fef7aa613ec49b499f1ad3f0da393c63271a98da0ae69a43f049017fb664736f6c634300081c0033";

  
      type StringConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: StringConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class String__factory extends ContractFactory {
    
      constructor(...args: StringConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<String & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): String__factory {
      return super.connect(runner) as String__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): StringInterface {
      return new Interface(_abi) as StringInterface;
    }
    
    override attach(address: string | Addressable): String {
      return super.attach(address) as String;
    }
  static connect(address: string, runner?: ContractRunner | null): String {
      return new Contract(address, _abi, runner) as unknown as String;
    }
  }

  
  